print("hello world")
print("hello woosung")
print("whdntjd011@naver.com")
print("*")
print("**")
print("***")
print("*****")
print("******")

print("******")
print("*****")
print("****")
print("***")
print("**")
print("*")

print("*************************")
print("*\t 성적표 \t*")
print("*************************")
print("*  국어    50\t\t*")
print("*************************")
print("*  영어    50\t\t*")
print("*************************")
print("*  수학    50\t\t*")
print("*************************")
print("*컴퓨터 학과\t 홍길동 *")
print("*************************")

print("일 \t 월 \t 화 \t 수 \t 목 \t 금 \t 토")
print("1 \t 2 \t 3 \t 4 \t 5 \t 6 \t 7")
print("8 \t 9 \t 10 \t 11 \t 12 \t 13 \t 14")
print("15 \t 16 \t 17 \t 18 \t 19 \t 20 \t 21")
print("22 \t 23 \t 24 \t 25 \t 26 \t 27 \t 28")
print("29 \t 30 \t 31")
print("woosung good")

